### PR TITLE
implement writing gajim keys

### PR DESCRIPTION
**Pull request by RalfJung**
This adds support for writing OTR keys and fingerprints in a format Gajim can understand. I successfully used it to convert my data from Pidgin.

### CODE REVIEW

**Comment by RalfJung** [comment]
Did you try the tests again with the latest version of this pull request? At least one of the two errors you saw should be fixed now. The other one I still cannot reproduce, nor explain from the code why it happens. Any help would be appreciated.

**Comment by eighthave** [comment]
This version gets further but doesn't complete on Ubuntu/precise. You can install Debian/wheezy using virtualbox or a chroot to test.  On Ubuntu/precise, I'm still getting an error using 37eb48573f81f12ff7e1f56d3cd29d89d8f2d31b

```
------------------------------------------------------------------------
Convert jitsi to gajim 
------------------------------------------------------------------------
/media/share/code/guardianproject/keysync/otrapps/__init__.py:7: UserWarning: Module otrapps was already imported from /media/share/code/guardianproject/keysync/otrapps/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import get_distribution, DistributionNotFound
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Reading jitsi files...
Traceback (most recent call last):
  File "./keysync", line 120, in <module>
    main()
  File "./keysync", line 117, in main
    properties.write(keydict, args.output_folder)
  File "/media/share/code/guardianproject/keysync/otrapps/gajim.py", line 148, in write
    private_key = potr.compatcrypto.DSAKey((key['y'], key['g'], key['p'], key['q'], key['x']), private=True)
KeyError: 'x'
```

**Comment by eighthave** [comment]
On Debian/wheezy, I get this:

```
"y" values for "gptest@jabber.org" did not match: 
	"35543105673522282110752002253813479452905133508193941410990859530443238642500230446269807039770286136339287143095668990202930927624000487909158422536678900716435949126169846727188228921538781168995423865810232152543951498229945144506815184856354911724874120708375199660565550097425960343057438467920202810726" != "38040856360510125350394301399958983696973829490016276430386526840985952107881867889142620211269932029159268699586649556572847346109022108549170202157901213324391314367500980885885684693853872746469818094030430379634018524914111928010202041618887058353424621692200079417282114049708712536614154256514300774665"
Reading xchat files...
Traceback (most recent call last):
  File "./keysync", line 120, in <module>
    main()
  File "./keysync", line 117, in main
    properties.write(keydict, args.output_folder)
  File "/var/lib/jenkins/workspace/keysync-eighthave/otrapps/gajim.py", line 125, in write
    + '" in "' + savedir + '"')
Exception: Cannot find "config" in "/tmp/keysync-RtNtTfFi51othz/merge-into-gajim"
```

**Comment by RalfJung** [comment]
The "file not found" still does not make much sense when looking at the code: It should not even look for `/tmp/keysync-RtNtTfFi51othz/merge-into-gajim/config`, but for `/tmp/config`. That's what `main` says the `savedir` is. That's also what it does on my system. Do you have any idea what could be changing that on your machine?

The `KeyError` means that you have a key that has a `y`, but not an `x`. The jitsi dataset in the repository does not contain an account where the account itself has such a key (as opposed to a contact). Which dataset are you testing in?

In any case, I pushed an update that should fix this.

**Comment by eighthave** [comment]
The tests pass on my machine, now waiting for our Jenkins machine.  Looking at
your fix, I'm surprised that the tests ever passed on your machine.  If so,
that means that there are some cases in the tests that aren't working properly.

**Comment by RalfJung** [comment]
You find me just as surprised as yourself ;-) . Maybe there are some tools/libraries I do not have installed, that result in some tests being skipped?

**Pull request merged**
